//---------- Mandatory skill's include ----------
#include <pluginlib/class_list_macros.h>//Plugin export library
#include <ros/ros.h>
#include "skiros_skill/skill_base.h"    //Base template for all skills
#include "skiros_common/logger_sys.h"   //Skiros logging system
#include "skiros_config/param_types.h"  //Default parameters
#include "skiros_config/declared_uri.h" //Default world model URIs (Unified Resource Identifier) -> generated by skiros_world_model/generate_uri
#include "skiros_world_model/reasoners_loading_func.h"
//---------- Mandatory skill's include end ----------



namespace skiros_skill
{


/*!
 * \brief The base class for all drive skills. Defines common use variables
 *
 * Params: \n
 *  target - Target object to drive to \n
 *  mobileBase - Mobile base to move \n
 *
 */
class Drive : public SkillBase
{
public:
    /*!
      Here should be defined:
        -name, description, version
        -skill's parameters
      */
    Drive();
    virtual ~Drive() {}

    /*!
      Here should be defined:
        -pre-/post- conditions
        -persistents ROS listeners/advertiser
      */
    virtual bool onInit();

    //! Execute a sensing routine before the pre-condition check
    virtual int preSense();

    //! Skill's main execution routine
    virtual int execute();
protected:

    skiros_wm::Element target_object_;
    skiros_wm::Element target_location_;
    skiros_wm::Element initial_location_;
    skiros_wm::Element mobile_base_;
}; // class


} // skiros_skill
