//---------- Mandatory skill's include ----------
#include <pluginlib/class_list_macros.h>//Plugin export library
#include <ros/ros.h>
#include "skiros_skill/skill_base.h"    //Base template for all skills
#include "skiros_common/logger_sys.h"   //Skiros logging system
#include "skiros_config/param_types.h"  //Default parameters
#include "skiros_config/declared_uri.h" //Default world model URIs (Unified Resource Identifier) -> generated by skiros_world_model/generate_uri
//---------- Mandatory skill's include end ----------

#include "skiros_world_model/reasoners_loading_func.h"

namespace skiros_skill
{
using namespace skiros_config::owl;
using namespace skiros_wm;

/*!
 * \brief The base class for all pick skills. Defines common use variables
 *
 * Params: \n
 *  Arm - Arm to use \n
 *  Gripper - Gripper to use \n
 *  CameraUp - Upper workspace camera \n
 *  Container - Container to get the object from \n
 *
 */
class Pick : public skiros_skill::SkillBase
{
public:

    /*!
      Here should be defined:
        -name, description, version
        -skill's parameters
      */
    Pick();
    virtual ~Pick() {}

    /*!
      Here should be defined:
        -pre-/post- conditions
        -persistents ROS listeners/advertiser
      */
    virtual bool onInit();

    virtual int preSense();

    virtual int execute()
    {
        return 1;
    }

    virtual int postSense()
    {
        return 1;
    }

protected:

    //Common variables
    skiros_wm::Element grasping_pose_;
    skiros_wm::Element container_;
    skiros_wm::Element objObject;
    skiros_wm::Element camera_up_;
    skiros_wm::Element camera_arm_;
    skiros_wm::Element arm_;
    skiros_wm::Element gripper_;
    skiros_wm::ReasonerPtrType reasoner_;

}; // class

} // skiros_skill
